Refactor component to use new token structure
selsa-inube/inubekit-skeleton pull request #4
Opened 2024-03-06 16:53 UTC by cmarin001

This pull request encompasses a comprehensive refactor of a specific UI component within our application to align it with a newly introduced token structure. This strategic update is aimed at enhancing the component's design consistency, scalability, and maintainability by leveraging the advanced capabilities provided by the new design tokens.

2024-03-06 18:34 UTC, JanuarAsprilla approved these changes

2024-03-06 18:39 UTC, JanuarAsprilla commented on src/SkeletonIcon/SkeletonIcon.stories.tsx
> +const Default = (args: ISkeletonIconProps) => <SkeletonIcon {...args} />;
change `ISkeletonIconProps` to `ISkeletonIcon`.
make this change wherever that interface is located

2024-03-06 19:11 UTC, cmarin001 commented on src/SkeletonIcon/SkeletonIcon.stories.tsx
> +const Default = (args: ISkeletonIconProps) => <SkeletonIcon {...args} />;
solved

2024-03-06 20:02 UTC, JanuarAsprilla approved these changes

2024-03-07 03:10 UTC, wfercanas requested changes

2024-03-07 03:10 UTC, wfercanas commented on src/SkeletonIcon/styles.js
> +      ${theme?.skeleton?.animation?.color || inube.skeleton.animation.color} 80%
Check the animation because it doesn't look like the one we had before.

We're animating the background property, so I guess we must start with skeleton.background.color at 0%, change it to skeleton.animation.color at 50% and end with background.color again at 100%.

2024-03-07 03:10 UTC, wfercanas commented on src/SkeletonLine/styles.js
> +      ${theme?.skeleton?.animation?.color || inube.skeleton.animation.color} 80%
This animation has the same issue as skeletonIcon

2024-03-07 15:50 UTC, cmarin001 commented on src/SkeletonIcon/styles.js
> +      ${theme?.skeleton?.animation?.color || inube.skeleton.animation.color} 80%
solved

2024-03-07 15:50 UTC, cmarin001 commented on src/SkeletonLine/styles.js
> +      ${theme?.skeleton?.animation?.color || inube.skeleton.animation.color} 80%
solved

2024-03-07 18:51 UTC, wfercanas approved these changes

2024-03-07 18:51 UTC, merged